services:
  - type: web
    name: golden-forecast
    env: docker
    repo: https://github.com/juandelaf1/Golden-Forecast
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "8050"
